# Generated by Django 5.2.1 on 2025-05-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10)),
                ('secretcode', models.CharField()),
                ('content', models.TextField(default='')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
